### ISSUE TITLE
Automatic Formatting

### ISSUE THREAD

**Issue by regr4** [lhl2617/VSLilyPond-snippets#3]
Is there a way to have automatic formatting? 
Right now, if I choose the option 'format document' from the command palette I get the message 'There is no formatter for 'lilypond' files installed.'
Would it be possible to implement autoformatting?
If it isn't too hard, I could maybe help adding it in.

**Comment by lhl2617** [comment]
Hi @regr4, thanks for the issue. I haven't looked into adding it (currently focused on other projects). If you are interested, feel free to make the formatter - a PR into [the main repo](https://github.com/lhl2617/VSLilyPond) would be very welcome. You could also make a separate formatter extension if you wish to own the project, and I can add it to my extension pack 😄

**Comment by regr4** [comment]
Well,
I have exactly zero experience with typescript vscode extensions, but I guess I'll just dive into this headfirst. I don't think I'll publish it on my own, since I don't want to set up an Azure? account just for this. You may or may not get a pull request eventually. I can't promise anything though 🙃

**Comment by lhl2617** [comment]
Thanks! I'll let you know if I start it so we can work together, do update me if you have any progress 😃

**Comment by lhl2617** [comment]
https://github.com/frescobaldi/frescobaldi/blob/ef987bf12324ae784806ffb9db548383c58665ec/frescobaldi_app/reformat.py

You can find Frescobaldi's implementation here if you wish to refer - it is GPLv2. 

You'll need to find corresponding functionality in VSCode (VSCode API is reasonably well-documented). It is not difficult to start a new extension nowadays with the well-written tutorials. Do message me if you need any help! 🔥

**Comment by regr4** [comment]
Nice, I hadn't thought of that! Open source software is really convenient!
So basically, what's left to do is:
- Translate it from Python into Typescript
- Change it to use the vscode API
Is there anything else?

**Comment by lhl2617** [comment]
Yep - it isn't as simple as it would sound like (Python-TypeScript conversion), but you can refer to its architecture. I've not had time to look at it closely but I'm sure it's not that complex.

**Comment by lhl2617** [comment]
https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

Here's a rather old (but still relevant-looking) blog post about a formatting extension in VSCode

**Comment by lhl2617** [comment]
Hey @regr4 ! Just FYI that I've made a formatter extension that depends on Frescobaldi's (`python-ly`, actually) codebase:

https://marketplace.visualstudio.com/items?itemName=lhl2617.lilypond-formatter

you can check the repo here:
https://github.com/lhl2617/VSLilyPond-formatter
